<a href="https://colab.research.google.com/github/V3rmili/data-science-bootcamp/blob/main/Nauka1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
print("Hello Colab")

Hello Colab


In [3]:
x = np.random.randn(10, 5)

print(x)

[[ 0.97371467  1.38344623  0.64208476  0.14589547  0.0193656 ]
 [ 1.48442076 -0.84293703 -0.08390966 -0.11718085  0.3869352 ]
 [ 1.30623748 -0.11764586 -1.90911962 -0.80766233  0.40647416]
 [-0.15114601 -0.12668003 -0.34911011  1.81685756 -1.02583891]
 [-0.2421945  -1.38246185 -0.60607093  0.24548146  0.70868386]
 [ 0.30578071 -1.87884358  1.07260195  0.99240891 -0.40350678]
 [-0.91893663 -0.26085955 -1.66851543 -1.82935375 -0.82567906]
 [ 1.0482585  -0.85186879  0.01527953 -0.78912693 -0.08454957]
 [ 1.80496462  1.15910497  0.21372849 -1.18982104 -1.40255053]
 [ 0.59348687 -0.448697    1.30840215  0.59278234 -0.41604571]]


In [10]:
np.ndarray(3, dtype=int)

array([4604930618986332160, 4604930618986332160,                   0])

In [9]:
x.ndim



2